
import { Category } from './types';

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'restaurants',
    titleAr: 'المطاعم والكافيهات',
    titleEn: 'Restaurants & Cafes',
    icon: 'Utensils',
    subCategories: ['جلسات داخلية', 'عائلية', 'وجبات سريعة', 'كفتيريات', 'مقاهي', 'كرك']
  },
  {
    id: 'supermarkets',
    titleAr: 'سوبرماركت وبرادات',
    titleEn: 'Supermarkets & Coldstores',
    icon: 'ShoppingCart',
    subCategories: ['سوبرماركت', 'برادات صغيرة', 'خضار وفواكه']
  },
  {
    id: 'health',
    titleAr: 'الصحة',
    titleEn: 'Health',
    icon: 'HeartPulse',
    subCategories: ['مراكز صحية', 'عيادات', 'صيدليات']
  },
  {
    id: 'cars',
    titleAr: 'السيارات',
    titleEn: 'Automotive',
    icon: 'Car',
    subCategories: ['تصليح', 'تأجير', 'بيع سيارات', 'دراجات نارية']
  },
  {
    id: 'shopping',
    titleAr: 'تسوق وأقسام أخرى',
    titleEn: 'Shopping & Others',
    icon: 'ShoppingBag',
    subCategories: ['ملابس', 'ذهب', 'إلكترونيات', 'أثاث', 'نظارات', 'مكتبات', 'محلات رياضية']
  },
  {
    id: 'services',
    titleAr: 'خدمات ترفيهية وعقارات',
    titleEn: 'Leisure & Real Estate',
    icon: 'Home',
    subCategories: ['صالات ألعاب', 'GYM', 'سفريات', 'صالونات', 'فنادق', 'شقق', 'مكاتب', 'عقارات']
  }
];

export const TRANSLATIONS = {
  ar: {
    searchPlaceholder: "ابحث بالاسم، المنطقة، أو رقم المجمع...",
    home: "الرئيسية",
    admin: "لوحة التحكم",
    results: "النتائج",
    noResults: "لا توجد نتائج مطابقة لبحثك.",
    contact: "اتصل بنا",
    maps: "خرائط جوجل",
    instagram: "إنستغرام",
    phone: "رقم الهاتف",
    block: "مجمع",
    area: "المنطقة",
    manageAds: "إدارة الإعلانات",
    manageBusinesses: "إدارة المنشآت",
    manageMembers: "إدارة الأعضاء",
    manageCategories: "إدارة الأقسام",
    syncSheet: "ربط جوجل شيت",
    addBusiness: "إضافة منشأة جديدة",
    addCategory: "إضافة قسم جديد",
    addMember: "إضافة عضو جديد",
    save: "حفظ",
    cancel: "إلغاء",
    edit: "تعديل",
    delete: "حذف",
    username: "اسم المستخدم",
    password: "كلمة المرور",
    role: "الصلاحية",
    syncNow: "تحديث البيانات الآن",
    sheetUrl: "رابط ملف CSV لجوجل شيت",
    syncSuccess: "تم تحديث البيانات بنجاح من جوجل شيت",
    syncError: "فشل في تحديث البيانات. تأكد من الرابط",
    exportData: "تصدير البيانات",
    allCategories: "كل الأقسام",
    exportCSV: "تصدير إلى CSV",
    exportXLSX: "تصدير إلى XLSX (Excel)",
    selectCategory: "اختر القسم للتصدير",
    downloadTemplate: "تحميل قالب الإدخال (Excel)",
    templateInstructions: "استخدم هذا الملف كنموذج، ارفعه على Google Sheets، ثم انشره كـ CSV.",
    subCategories: "التفرعات",
    addSubCategory: "إضافة تفرع",
    categoryIcon: "أيقونة القسم",
    titleAr: "الاسم (بالعربي)",
    titleEn: "الاسم (بالإنجليزي)",
    reports: "التقارير والإحصائيات",
    totalBusinesses: "إجمالي المنشآت",
    totalMembers: "إجمالي الأعضاء",
    totalVisitors: "إجمالي الزوار",
    businessesByCategory: "المنشآت حسب القسم",
    membersByRole: "الأعضاء حسب الصلاحية",
    statsOverview: "نظرة عامة على الإحصائيات",
    activeAds: "الإعلانات النشطة",
    backupRestore: "النسخ الاحتياطي والاستعادة",
    backupNow: "تحميل نسخة احتياطية",
    restoreNow: "استعادة من نسخة احتياطية",
    restoreWarning: "تحذير: هذه العملية ستقوم باستبدال كافة البيانات الحالية بالبيانات الموجودة في الملف المختار. هل تريد الاستمرار؟",
    restoreSuccess: "تمت استعادة البيانات بنجاح",
    restoreError: "فشل في استعادة البيانات. يرجى التأكد من صحة الملف المختار",
    dataBackup: "نسخة احتياطية للبيانات",
    maxAdsTop: "أقصى عدد للإعلانات (أعلى)",
    maxAdsMiddle: "أقصى عدد للإعلانات (منتصف)",
    maxAdsBottom: "أقصى عدد للإعلانات (أسفل)",
    adDisplaySettings: "إعدادات عرض الإعلانات",
    rating: "التقييم",
    rateThis: "قيم هذه المنشأة",
    thankYouRating: "شكراً لتقييمك!",
    averageRating: "متوسط التقييم",
    deleteSelected: "حذف المنشآت المختارة",
    selectAll: "تحديد الكل",
    confirmBulkDelete: "هل أنت متأكد من حذف {n} منشأة مختارة؟",
    bulkDeleteSuccess: "تم حذف المنشآت بنجاح",
    isPriority: "منشأة مميزة (في الأعلى)",
    // New features translations
    backToIndex: "العودة إلى القائمة",
    callNow: "اتصل الآن",
    specialOffer: "عرض خاص",
    validUntil: "صالح حتى",
    ongoing: "مستمر",
    newOpening: "افتتاح جديد",
    trendingThisWeek: "التريند هذا الأسبوع",
    featured: "راعي مميز",
    openNow: "مفتوح الآن",
    cuisine: "نوع المطبخ",
    priceRange: "فئة السعر",
    parking: "مواقف متوفرة",
    dressCode: "الزي المفضل",
    familySection: "قسم العائلات",
    reviewsAndComments: "التقييمات والتعليقات",
    writeReview: "اكتب تقييماً",
    authorName: "الاسم",
    commentPlaceholder: "اكتب رأيك وتجربتك هنا...",
    submitReview: "نشر التقييم",
    noReviewsYet: "لا توجد تقييمات بعد. كن أول من يضيف تقييماً!",
    saveToFavorites: "حفظ في المفضلة",
    favoritesPageTitle: "المنشآت المفضلة لديك",
    loginRequired: "يرجى تسجيل الدخول أولاً لحفظ المفضلة",
    favorites: "المفضلة",
    userLogin: "تسجيل دخول الأعضاء",
    userRegister: "إنشاء حساب جديد",
    login: "تسجيل الدخول",
    logout: "تسجيل الخروج",
    register: "تسجيل حساب",
    allCuisines: "كل المطابخ",
    allAreas: "كل المناطق",
    allPrices: "كل الأسعار",
    ratingCountText: "تقييم"
  },
  en: {
    searchPlaceholder: "Search by name, area, or block number...",
    home: "Home",
    admin: "Admin",
    results: "Results",
    noResults: "No results found.",
    contact: "Contact Us",
    maps: "Google Maps",
    instagram: "Instagram",
    phone: "Phone Number",
    block: "Block",
    area: "Area",
    manageAds: "Manage Ads",
    manageBusinesses: "Manage Businesses",
    manageMembers: "Manage Members",
    manageCategories: "Manage Categories",
    syncSheet: "Google Sheets Sync",
    addBusiness: "Add New Business",
    addCategory: "Add New Category",
    addMember: "Add New Member",
    save: "Save",
    cancel: "Cancel",
    edit: "Edit",
    delete: "Delete",
    username: "Username",
    password: "Password",
    role: "Role",
    syncNow: "Sync Data Now",
    sheetUrl: "Google Sheet CSV URL",
    syncSuccess: "Data synced successfully from Google Sheets",
    syncError: "Failed to sync data. Please check the URL",
    exportData: "Export Data",
    allCategories: "All Categories",
    exportCSV: "Export to CSV",
    exportXLSX: "Export to XLSX (Excel)",
    selectCategory: "Select Category to Export",
    downloadTemplate: "Download Input Template (Excel)",
    templateInstructions: "Use this file as a template, upload it to Google Sheets, then publish as CSV.",
    subCategories: "Sub-Categories",
    addSubCategory: "Add Sub-Category",
    categoryIcon: "Category Icon",
    titleAr: "Title (AR)",
    titleEn: "Title (EN)",
    reports: "Reports & Stats",
    totalBusinesses: "Total Businesses",
    totalMembers: "Total Members",
    totalVisitors: "Total Visitors",
    businessesByCategory: "Businesses by Category",
    membersByRole: "Members by Role",
    statsOverview: "Statistics Overview",
    activeAds: "Active Ads",
    backupRestore: "Backup & Restore",
    backupNow: "Download Full Backup",
    restoreNow: "Restore from Backup",
    restoreWarning: "Warning: This action will overwrite all current data with the data from the selected file. Do you want to proceed?",
    restoreSuccess: "Data restored successfully",
    restoreError: "Failed to restore data. Please ensure you selected a valid backup file.",
    dataBackup: "Data Backup",
    maxAdsTop: "Max Ads (Top)",
    maxAdsMiddle: "Max Ads (Middle)",
    maxAdsBottom: "Max Ads (Bottom)",
    adDisplaySettings: "Ad Display Settings",
    rating: "Evaluation",
    rateThis: "Rate this business",
    thankYouRating: "Thank you for your rating!",
    averageRating: "Average Rating",
    deleteSelected: "Delete Selected Businesses",
    selectAll: "Select All",
    confirmBulkDelete: "Are you sure you want to delete {n} selected businesses?",
    bulkDeleteSuccess: "Businesses deleted successfully",
    isPriority: "Priority Business (Pin to top)",
    // New features translations
    backToIndex: "Back to List",
    callNow: "Call Now",
    specialOffer: "Special Offer",
    validUntil: "Valid Until",
    ongoing: "Ongoing",
    newOpening: "New Opening",
    trendingThisWeek: "Trending This Week",
    featured: "Featured",
    openNow: "Open Now",
    cuisine: "Cuisine Type",
    priceRange: "Price Range",
    parking: "Parking Available",
    dressCode: "Dress Code",
    familySection: "Family Section",
    reviewsAndComments: "Reviews & Comments",
    writeReview: "Write a Review",
    authorName: "Your Name",
    commentPlaceholder: "Write your honest feedback here...",
    submitReview: "Submit Review",
    noReviewsYet: "No reviews yet. Be the first to leave one!",
    saveToFavorites: "Save to Favorites",
    favoritesPageTitle: "Your Favorite Businesses",
    loginRequired: "Please log in first to save favorites",
    favorites: "Favorites",
    userLogin: "User Login",
    userRegister: "Create New Account",
    login: "Log In",
    logout: "Log Out",
    register: "Register",
    allCuisines: "All Cuisines",
    allAreas: "All Areas",
    allPrices: "All Prices",
    ratingCountText: "ratings"
  }
};
