
import { Business, Ad } from './types';

export const INITIAL_BUSINESSES: Business[] = [
  {
    id: '1',
    nameAr: 'كفتيريا النور',
    nameEn: 'Al Noor Cafeteria',
    category: 'restaurants',
    subCategory: 'كفتيريات',
    areaAr: 'المنامة',
    areaEn: 'Manama',
    block: '304',
    phone: '17220000',
    instagram: 'alnoor_bh',
    googleMapsUrl: 'https://maps.google.com/?q=Manama+Block+304',
    image: 'https://picsum.photos/seed/cafe/400/300',
    hasAdPage: true,
    adPageContent: 'عرض خاص: اشترِ وجبتين واحصل على الثالثة مجاناً!',
    createdAt: '2026-05-15', // New!
    cuisine: 'Fast Food',
    cuisineAr: 'وجبات سريعة',
    priceRange: '$',
    openTime: '06:00',
    closeTime: '23:30',
    hasParking: true,
    hasFamilySection: false,
    dressCodeEn: 'Casual',
    dressCodeAr: 'غير رسمي',
    views: 45,
    ratingSum: 18,
    ratingCount: 4,
    reviews: [
      { id: 'r1', author: 'Ahmed', rating: 5, comment: 'أفضل شاورما في المنامة!', createdAt: '2026-05-20' },
      { id: 'r2', author: 'Sarah', rating: 4, comment: 'Nice local cafeteria, quick service.', createdAt: '2026-05-22' }
    ]
  },
  {
    id: '4',
    nameAr: 'مطعم سيكوس الإيطالي',
    nameEn: "Cico's Italian Restaurant",
    category: 'restaurants',
    subCategory: 'جلسات داخلية',
    areaAr: 'الجفير',
    areaEn: 'Juffair',
    block: '324',
    phone: '17711111',
    instagram: 'cicos_bh',
    googleMapsUrl: 'https://maps.google.com/?q=Cicos+Adliya+Bahrain',
    image: 'https://picsum.photos/seed/italian/400/300',
    isFeatured: true,
    isPriority: true,
    createdAt: '2025-12-01',
    cuisine: 'Italian',
    cuisineAr: 'إيطالي',
    priceRange: '$$$',
    openTime: '12:00',
    closeTime: '23:00',
    hasParking: true,
    hasFamilySection: true,
    dressCodeEn: 'Smart Casual',
    dressCodeAr: 'أنيق غير رسمي',
    views: 312,
    ratingSum: 23,
    ratingCount: 5,
    reviews: [
      { id: 'r3', author: 'Mark', rating: 5, comment: 'Authentic Italian taste and great ambiance.', createdAt: '2026-05-10' },
      { id: 'r4', author: 'خليل', rating: 4, comment: 'ممتاز جداً والبيتزا رائعة.', createdAt: '2026-05-14' }
    ]
  },
  {
    id: '5',
    nameAr: 'لانترنز جورميه',
    nameEn: 'Lanterns Gourmet Lounge',
    category: 'restaurants',
    subCategory: 'عائلية',
    areaAr: 'الرفاع',
    areaEn: 'Riffa',
    block: '905',
    phone: '17590000',
    instagram: 'lanterns_bh',
    googleMapsUrl: 'https://maps.google.com/?q=Lanterns+Riffa',
    image: 'https://picsum.photos/seed/indian/400/300',
    isFeatured: true,
    createdAt: '2026-05-20', // Recent!
    cuisine: 'Indian',
    cuisineAr: 'هندي',
    priceRange: '$$',
    openTime: '11:30',
    closeTime: '01:00', // Closes after midnight
    hasParking: true,
    hasFamilySection: true,
    dressCodeEn: 'Smart Casual',
    dressCodeAr: 'أنيق غير رسمي',
    views: 420,
    ratingSum: 14,
    ratingCount: 3,
    reviews: [
      { id: 'r5', author: 'Ali', rating: 5, comment: 'The butter chicken is out of this world.', createdAt: '2026-05-22' }
    ]
  },
  {
    id: '6',
    nameAr: 'أروها كافيه',
    nameEn: 'Aroha Cafe',
    category: 'restaurants',
    subCategory: 'مقاهي',
    areaAr: 'المحرق',
    areaEn: 'Muharraq',
    block: '208',
    phone: '17888888',
    instagram: 'aroha_cafe',
    googleMapsUrl: 'https://maps.google.com/?q=Muharraq',
    image: 'https://picsum.photos/seed/cafe2/400/300',
    createdAt: '2026-05-25', // Very recent!
    cuisine: 'Cafe',
    cuisineAr: 'مقاهي',
    priceRange: '$$',
    openTime: '07:30',
    closeTime: '00:00',
    hasParking: false,
    hasFamilySection: true,
    dressCodeEn: 'Casual',
    dressCodeAr: 'غير رسمي',
    views: 185,
    ratingSum: 8,
    ratingCount: 2,
    reviews: []
  },
  {
    id: '2',
    nameAr: 'صيدلية البحرين',
    nameEn: 'Bahrain Pharmacy',
    category: 'health',
    subCategory: 'صيدليات',
    areaAr: 'الرفاع',
    areaEn: 'Riffa',
    block: '901',
    phone: '17770000',
    googleMapsUrl: 'https://maps.google.com/?q=Riffa+Block+901',
    image: 'https://picsum.photos/seed/health/400/300'
  },
  {
    id: '3',
    nameAr: 'سوبرماركت العائلة',
    nameEn: 'Family Supermarket',
    category: 'supermarkets',
    subCategory: 'سوبرماركت',
    areaAr: 'المحرق',
    areaEn: 'Muharraq',
    block: '202',
    phone: '17330000',
    instagram: 'family_market',
    googleMapsUrl: 'https://maps.google.com/?q=Muharraq+Block+202',
    image: 'https://picsum.photos/seed/market/400/300',
    isPriority: true
  }
];

export const INITIAL_ADS: Ad[] = [
  { id: 'ad1', title: 'Top Banner', imageUrl: 'https://picsum.photos/seed/ad1/1200/300', mediaType: 'image', link: '#', active: true, position: 'top', heightClass: 'h-40' },
  { id: 'ad2', title: 'Middle Ad', imageUrl: 'https://picsum.photos/seed/ad2/800/400', mediaType: 'image', link: '#', active: true, position: 'middle', heightClass: 'h-64' },
  { id: 'ad3', title: 'Special Video', videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4', mediaType: 'video', link: '#', active: true, position: 'bottom', heightClass: 'h-60' },
];
